---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Site Data
- type: document
  path: content/pages/general.json
  label: General
- type: document
  path: content/data/shared.json
  label: Shared
- type: heading
  label: Content
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post-front-matter
- type: directory
  path: content/pages
  label: Pages
  create: documents
  match: "**/*"
  exclude: general.json
  new_doc_ext: json
  templates:
  - page-about
  - page-blog
  - page-contact
  - page-explore
  - page-get-involved
  - page-awards
  - page-index
  - page-terms
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - NODE_ENV=production
  - SERVER_ENV=production
  - SLATE_KEY=SLAbf984977-fba2-4989-881d-5af21f29f777TE
  preview_output_directory: dist
  install_dependencies_command: npm ci
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run generate
